### ISSUE TITLE
Maximum games?

### ISSUE THREAD

**Issue by whip28** [justMaku/gpghax#17]
What is the maximum of games that can add?

**Comment by justMaku** [comment]
Currently there's a limit of maximum 25 games but there exist (even more unsafe) solutions to remove this limitation, but I would advise against using them at the moment.

**Comment by alucard73** [comment]
I think it's 25 max, so directory from 21 to 25. I saw a scrip that allows to extract a file that once edit could put 50 game, but I did not test. The last script that I tried to make a backup of the image.img nand destroyed my usb and now I have to buy another usb key because it is no longer recognized by my pc
